# Generated by Django 3.2.18 on 2024-02-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
        ),
    ]
