# Generated by Django 3.2.18 on 2024-02-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], max_length=2),
        ),
    ]
