# Generated by Django 3.2.18 on 2024-02-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_alter_volunteer_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='branch',
            field=models.CharField(choices=[('CO', 'Computer'), ('AI', 'AIDS'), ('DS', 'Computer (DS)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], max_length=2),
        ),
    ]
