# Generated by Django 3.2.18 on 2024-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20240222_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='branch',
            field=models.CharField(choices=[('Computer', 'Computer Engineering'), ('AIDS', 'Artificial Intelligence and Data Science'), ('CDS', 'Computer (DS)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='event',
            field=models.CharField(choices=[('Website Design Portfolio Showcase', 'Website Design Portfolio Showcase'), ('Poster Competition', 'Poster Competition'), ('Coding Challange', 'Coding Challenge'), ('Tech Trivia Showdown (Tech-Quiz)', 'Tech Trivia Showdown (Tech-Quiz)'), ('Tech-Debate', 'Tech-Debate'), ('Treasure Hunt/CTF', 'Treasure Hunt/CTF'), ('Project Competition', 'Project Competition'), ('Esports Tournament', 'Esports Tournament')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], max_length=2),
        ),
    ]
