# Generated by Django 3.2.18 on 2024-02-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_auto_20240222_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='registration_for',
            field=models.CharField(choices=[('Club Member', 'Club Member'), ('Event Volunteer', 'Event Volunteer')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
